on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug dist
        run: ls -la dist

      # Work‑around GH registry glitch: explicitly pull upload‑artifact@v3
      - name: Prefetch upload‑artifact action
        uses: actions/upload-artifact@v3
        with:
          name: dummy-artifact
          path: README.md

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist